[package]

name = "src"
version = "0.1.0"
edition = "2021"

[features]

default = ["keyboard_controls"]
keyboard_controls = []
raspberry_pi = ["dep:rppal"]

[dependencies]

bevy = "0.14.2"
rand = "0.8.4"
rppal = { version = "0.19.0", optional = true }